name: PyBOMBS Dev Image - Manual Docker Hub Push
on:
  workflow_dispatch:
    inputs:
      ubuntu_version:
        description: 'Ubuntu Version'
        required: true
        default: 'jammy'
      gr_version:
        description: 'GR Version'
        required: true
        default: gnuradio310

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        env:
          IMG: ${{ secrets.DOCKERHUB_USERNAME }}/pybombs-dev
          TAG: ${{ github.event.inputs.gr_version }}-ubuntu-${{ github.event.inputs.ubuntu_version }}
        with:
          file: docker/pybombs-dev.dockerfile
          push: true
          platforms: linux/amd64
          build-args: |
            dist=ubuntu:${{ github.event.inputs.ubuntu_version }}
            gr_version=${{ github.event.inputs.gr_version }}
          tags: ${{ env.IMG }}:${{ env.TAG }}
          cache-from: type=registry,ref=${{ env.IMG }}:${{ env.TAG }}
          cache-to: type=inline